name: Python Flake8 and pylint code quality check

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install apt dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq python3 python3-pip
    - name: Add the bin directory pip uses for executables on PATH
      run: |
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint
        flake8 --version
        pylint --version
    - name: Lint with Flake8
      run: |
        flake8 --config=.flake8 --count --statistics --show-source .
    - name: Lint with Pylint
      run: |
        pylint .
    - name: Lint with Pylint - More strict, allowed to fail
      run: |
        pylint --rc-file=.pylintrc_allowed_to_fail .
